name: "Plugin Changes"

on:
  push:
    branches: ["main"]
    paths:
      - "src/Travelcase/**.cs"
      - "src/Travelcase/*.csproj"
      - "src/Travelcase/packages.lock.json"
      - "src/Sirensong/"
  pull_request:
    branches: ["main"]
    paths:
      - "src/Travelcase/**.cs"
      - "src/Travelcase/*.csproj"
      - "src/Travelcase/packages.lock.json"
      - "src/Sirensong/"
    types: [ready_for_review, opened, synchronize]
  workflow_dispatch:

jobs:
  Test:
    if: github.event.pull_request.draft == false || github.event_name == 'push'
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./src
    strategy:
        matrix:
          dotnet: [7.0.x]
          dalamud_version: ["latest", "stg/latest"]
    env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        DALAMUD_HOME: /tmp/dalamud
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Cache Nuget Packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Download Dalamud
        run: |
          wget https://goatcorp.github.io/dalamud-distrib/${{ matrix.dalamud_version }}.zip -O /tmp/dalamud.zip
          unzip /tmp/dalamud.zip -d ${{ env.DALAMUD_HOME }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: ${{ matrix.dotnet }}
        
      - name: Restore Nuget Packages
        run: dotnet restore

      - name: Build Plugin
        run: dotnet build --no-restore --nologo

      - name: Check for Lint Errors
        id: lint
        continue-on-error: true
        run: | 
          dotnet format --verify-no-changes > lint.txt 2>&1

      - name: Report Lint Errors
        if : steps.lint.outcome == 'failure'
        run: |
          cat lint.txt | sed -E 's/^(.*)$/::warning:: \1/g'

      - name: Run Tests
        run: dotnet test --no-restore --no-build --verbosity normal