name: "Push/PR: Tests"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [ready_for_review, opened, synchronize]

jobs:
  Build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Travelcase/
        shell: bash
    strategy:
      matrix:
        dotnet-version: [7.0.x]
    env:
      DALAMUD_HOME: /tmp/dalamud
      IsCI: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Download Dalamud Library
        run: |
          wget https://goatcorp.github.io/dalamud-distrib/latest.zip -O /tmp/dalamud.zip
          unzip /tmp/dalamud.zip -d /tmp/dalamud

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build plugin in debug mode
        run: dotnet build -c Debug --no-restore --nologo

      - name: Build plugin in release mode
        run: dotnet build -c Release --no-restore --nologo

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Build Artifacts
          path: Travelcase/bin/
